---
title: "R Notebook"
output:
  html_document: default
  html_notebook: default
---

```{r,message=FALSE, echo=FALSE}
source('../utils/load_libraries.R')
```

```{r, message=FALSE, echo=FALSE, cache=FALSE}
source('../utils/load_functions.R')
source('../utils/load_data.R')
library(heatmaply)
```

```{r}

get_extream_kinase = function(data, strain_code, num_top, get_highest_kinase=TRUE, expression_high_to_low = TRUE) {
  data_mean = rowMeans(data)
  data = data[order(data_mean, decreasing = expression_high_to_low),]
  id = apply(data,1,function(x) strain_code[order(x,decreasing = get_highest_kinase)][1:num_top])
  dim(id) <- NULL
  rank_df = data.frame(id,count=ave(id==id, id, FUN=cumsum))
  rank_order = rep(1:dim(data)[1], each=num_top)
  rank_df$rank_order = rank_order
  return(rank_df)
}


make_plot = function(data, meta, title){
  data = data[order(rowMeans(data)), ]
   top = get_extream_kinase(data, 
                            meta$Strain_Code, 
                            num_top =3, 
                            get_highest_kinase=FALSE, # Lowest
                            expression_high_to_low = TRUE)
   plot = ggplot(top%>%filter(rank_order < 50), aes(x=rank_order, y=count, group=id, color=id)) + geom_line() + labs(title = title) 
   return(plot) 
}













library(ggplot2)
vsd = vsd[,colData(vsd)$Drug == 'Cocktail']
meta = colData(vsd)
meta = as.data.frame(meta)
meta = meta %>% mutate(Condition = if_else(Stress=='None',
                                           as.character(Media),
                                           as.character(Stress)
))

meta$Condition = as.factor(meta$Condition)
x = assay(vsd)
x = x - rowMeans(x)
colnames(x) = meta$Sample_Name
data = x
l <- htmltools::tagList()
i=1
for(c in unique(meta$Condition)){
  temp_idx = which(meta$Condition == c)
  temp_data = data[,temp_idx]
  temp_meta = meta[temp_idx,]
  l[[i]] <- as.widget(ggplotly(make_plot(temp_data, temp_meta, title=c)))
  i = i + 1
}
l
```

Can we plot this as a heatmap too?

```{r}
ll <- htmltools::tagList()
i = 1
for(c in unique(meta$Condition)){
stress_specific = vsd[,meta$Condition == c]
stress_x = assay(stress_specific)
stress_x = rename_gene_names(stress_x,t2g)
stress_meta = colData(stress_specific)
colnames(stress_x) = stress_meta$Strain_Code
stress_wt = rowMedians(stress_x[,stress_meta$Strain=='WT'])
stress_ave = rowMeans(stress_x)
sd = apply(stress_x,1,sd)
# your pick here
sigma = apply(stress_x,2,function(x) (x-stress_wt)/sd)
sigma[sigma < 1 & sigma > -1] = 0
cond_de = (stress_ave - median(stress_wt))/sd(stress_wt)
#install.packages("d3heatmap")
ll[[i]] = as.widget(heatmaply(sigma[names(which(cond_de>2)),],main=c))
i = i+1
}
ll
```